{
 "title": "Discord Chat Activity",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "guildId",
    "query": "SELECT distinct guildId FROM discord.textChatLog"
   },
   {
    "name": "User",
    "query": "SELECT distinct authorName FROM discord.textChatLog"
   },
   {
    "name": "Channel",
    "query": "SELECT distinct channelName FROM discord.textChatLog"
   },
   {
    "name": "Granularity",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "authorId Link Mappings",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT distinct authorName, CONCAT(\"<@\", authorId, \">\") AS authorId\nFROM discord.textChatLog\nWHERE $__timeFilter(messageTimestamp)\n    AND (authorName IN ($User) OR \"All\" IN ($User))\n    AND (guildId IN ($guildId) OR \"All\" IN ($guildId))\n    AND (channelName IN ($Channel) OR \"All\" IN ($Channel))\nORDER BY authorName ASC"
    }
   ]
  },
  {
   "title": "channelId Mapping",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT distinct channelName, CONCAT(\"<\", channelId, \">\") AS channelId\nFROM discord.textChatLog\nWHERE $__timeFilter(messageTimestamp)\n    AND (authorName IN ($User) OR \"All\" IN ($User))\n    AND (guildId IN ($guildId) OR \"All\" IN ($guildId))\n    AND (channelName IN ($Channel) OR \"All\" IN ($Channel))\nORDER BY channelName ASC"
    }
   ]
  },
  {
   "title": "Messages By Channel Activity",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    channelName AS metric,\n    1 AS time,\n    count(*) AS messages\nFROM discord.textChatLog\nWHERE \n    $__timeFilter(messageTimestamp)\n    AND (authorName IN ($User) OR \"All\" IN ($User))\n    AND (guildId IN ($guildId) OR \"All\" IN ($guildId))\n    AND (channelName IN ($Channel) OR \"All\" IN ($Channel))\nGROUP BY channelName"
    }
   ]
  },
  {
   "title": "Messages By Channel",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    channelName AS metric,\n    CASE\n        WHEN '$Granularity' = '1m' THEN FROM_UNIXTIME(60 * FLOOR( UNIX_TIMESTAMP(messageTimestamp)/60))\n        WHEN '$Granularity' = '5m' THEN FROM_UNIXTIME(300 * FLOOR( UNIX_TIMESTAMP(messageTimestamp)/300))\n        WHEN '$Granularity' = '10m' THEN FROM_UNIXTIME(600 * FLOOR( UNIX_TIMESTAMP(messageTimestamp)/600))\n        WHEN '$Granularity' = '30m' THEN FROM_UNIXTIME(1800 * FLOOR( UNIX_TIMESTAMP(messageTimestamp)/1800))\n        WHEN '$Granularity' = '1h' THEN FROM_UNIXTIME(3600 * FLOOR( UNIX_TIMESTAMP(messageTimestamp)/3600))\n        WHEN '$Granularity' = '6h' THEN FROM_UNIXTIME(21600 * FLOOR( UNIX_TIMESTAMP(messageTimestamp)/21600))\n        WHEN '$Granularity' = '12h' THEN FROM_UNIXTIME(43200 * FLOOR( UNIX_TIMESTAMP(messageTimestamp)/43200))\n        WHEN '$Granularity' = '1d' THEN FROM_UNIXTIME(86400 * FLOOR( UNIX_TIMESTAMP(messageTimestamp)/86400))\n        WHEN '$Granularity' = '7d' THEN FROM_UNIXTIME(604800 * FLOOR( UNIX_TIMESTAMP(messageTimestamp)/604800))\n        WHEN '$Granularity' = '14d' THEN FROM_UNIXTIME(1209600 * FLOOR( UNIX_TIMESTAMP(messageTimestamp)/1209600))\n        WHEN '$Granularity' = '30d' THEN FROM_UNIXTIME(2592000 * FLOOR( UNIX_TIMESTAMP(messageTimestamp)/2592000))\n    END AS time,\n    count(*)\nFROM discord.textChatLog\nWHERE \n    $__timeFilter(messageTimestamp)\n    AND (authorName IN ($User) OR \"All\" IN ($User))\n    AND (guildId IN ($guildId) OR \"All\" IN ($guildId))\n    AND (channelName IN ($Channel) OR \"All\" IN ($Channel))\nGROUP BY channelName, time\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "User Message Activity By Channel",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    CONCAT(authorName, \"(\", channelName, \")\") AS metric,\n    CASE\n        WHEN '$Granularity' = '1m' THEN FROM_UNIXTIME(60 * FLOOR( UNIX_TIMESTAMP(messageTimestamp)/60))\n        WHEN '$Granularity' = '5m' THEN FROM_UNIXTIME(300 * FLOOR( UNIX_TIMESTAMP(messageTimestamp)/300))\n        WHEN '$Granularity' = '10m' THEN FROM_UNIXTIME(600 * FLOOR( UNIX_TIMESTAMP(messageTimestamp)/600))\n        WHEN '$Granularity' = '30m' THEN FROM_UNIXTIME(1800 * FLOOR( UNIX_TIMESTAMP(messageTimestamp)/1800))\n        WHEN '$Granularity' = '1h' THEN FROM_UNIXTIME(3600 * FLOOR( UNIX_TIMESTAMP(messageTimestamp)/3600))\n        WHEN '$Granularity' = '6h' THEN FROM_UNIXTIME(21600 * FLOOR( UNIX_TIMESTAMP(messageTimestamp)/21600))\n        WHEN '$Granularity' = '12h' THEN FROM_UNIXTIME(43200 * FLOOR( UNIX_TIMESTAMP(messageTimestamp)/43200))\n        WHEN '$Granularity' = '1d' THEN FROM_UNIXTIME(86400 * FLOOR( UNIX_TIMESTAMP(messageTimestamp)/86400))\n        WHEN '$Granularity' = '7d' THEN FROM_UNIXTIME(604800 * FLOOR( UNIX_TIMESTAMP(messageTimestamp)/604800))\n        WHEN '$Granularity' = '14d' THEN FROM_UNIXTIME(1209600 * FLOOR( UNIX_TIMESTAMP(messageTimestamp)/1209600))\n        WHEN '$Granularity' = '30d' THEN FROM_UNIXTIME(2592000 * FLOOR( UNIX_TIMESTAMP(messageTimestamp)/2592000))\n    END AS time,\n    count(*)\nFROM discord.textChatLog\nWHERE \n    $__timeFilter(messageTimestamp)\n    AND (authorName IN ($User) OR \"All\" IN ($User))\n    AND (guildId IN ($guildId) OR \"All\" IN ($guildId))\n    AND (channelName IN ($Channel) OR \"All\" IN ($Channel))\nGROUP BY authorName, channelName, time\nORDER BY time ASC"
    }
   ]
  }
 ]
}