{
 "title": "Discord Voice Activity",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "User",
    "query": "SELECT distinct userName FROM discord.voiceChatLog"
   },
   {
    "name": "Channel",
    "query": "SELECT distinct channelName FROM discord.voiceChatLog WHERE channelId IS NOT NULL"
   }
  ]
 },
 "panels": [
  {
   "title": "discordUserId Link Mappings",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT distinct userName, CONCAT(\"<@\", discordUserId, \">\") AS discordUserId\nFROM discord.voiceChatLog\nWHERE\n(\n    (UNIX_TIMESTAMP(joinChannelTimeStamp) < $__unixEpochFrom() AND (UNIX_TIMESTAMP(leaveChannelTimestamp) > $__unixEpochTo() OR leaveChannelTimestamp IS NULL))\n    OR $__timeFilter(joinChannelTimeStamp)\n    OR $__timeFilter(leaveChannelTimestamp)\n    OR\n    (\n        leaveChannelTimestamp IS NULL\n        AND (UNIX_TIMESTAMP(now()) - $__unixEpochTo()) <= 5\n    )\n)\nAND (userName IN ($User) OR \"All\" IN ($User))\nAND (channelName IN ($Channel) OR \"All\" IN ($Channel))"
    }
   ]
  },
  {
   "title": "channelId Mapping",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT distinct channelName, CONCAT(\"<\", channelId, \">\") AS channelId\nFROM discord.voiceChatLog\nWHERE\n(\n    (UNIX_TIMESTAMP(joinChannelTimeStamp) < $__unixEpochFrom() AND (UNIX_TIMESTAMP(leaveChannelTimestamp) > $__unixEpochTo() OR leaveChannelTimestamp IS NULL))\n    OR $__timeFilter(joinChannelTimeStamp)\n    OR $__timeFilter(leaveChannelTimestamp)\n    OR\n    (\n        leaveChannelTimestamp IS NULL\n        AND (UNIX_TIMESTAMP(now()) - $__unixEpochTo()) <= 5\n    )\n)\nAND (userName IN ($User) OR \"All\" IN ($User))\nAND (channelName IN ($Channel) OR \"All\" IN ($Channel))"
    }
   ]
  },
  {
   "title": "User Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT * FROM\n(\n    SELECT\n        userName AS metric,\n        CASE\n            WHEN channelId IS     NULL AND leaveChannelTimestamp IS     NULL THEN UNIX_TIMESTAMP(now())\n            WHEN channelId IS     NULL AND leaveChannelTimestamp IS NOT NULL THEN UNIX_TIMESTAMP(leaveChannelTimestamp)\n            WHEN channelId IS NOT NULL AND leaveChannelTimestamp IS     NULL THEN UNIX_TIMESTAMP(now())\n            WHEN channelId IS NOT NULL AND leaveChannelTimestamp IS NOT NULL THEN UNIX_TIMESTAMP(leaveChannelTimestamp)\n            ELSE 0\n        END AS \"time\",\n        CASE\n            WHEN channelId IS NULL THEN 0\n            WHEN leaveChannelTimestamp IS     NULL THEN (UNIX_TIMESTAMP(now()) - UNIX_TIMESTAMP(joinChannelTimeStamp))\n            WHEN leaveChannelTimestamp IS NOT NULL THEN (UNIX_TIMESTAMP(leaveChannelTimestamp) - UNIX_TIMESTAMP(joinChannelTimeStamp))\n            ELSE -1\n        END AS \"TimeSpent\"\n    FROM discord.voiceChatLog\n    WHERE\n        (\n            (UNIX_TIMESTAMP(joinChannelTimeStamp) < $__unixEpochFrom() AND (UNIX_TIMESTAMP(leaveChannelTimestamp) > $__unixEpochTo() OR leaveChannelTimestamp IS NULL))\n            OR $__timeFilter(joinChannelTimeStamp)\n            OR $__timeFilter(leaveChannelTimestamp)\n            OR\n            (\n                leaveChannelTimestamp IS NULL\n                AND (UNIX_TIMESTAMP(now()) - $__unixEpochTo()) <= 5\n            )\n        )\n        AND (userName IN ($User) OR \"All\" IN ($User))\n        AND (channelName IN ($Channel) OR \"All\" IN ($Channel) OR channelId IS NULL)\n    GROUP BY id\n    UNION\n    SELECT\n        userName AS metric,\n        UNIX_TIMESTAMP(joinChannelTimeStamp) AS \"time\",\n        CASE\n            WHEN channelId IS NULL THEN 0\n            WHEN leaveChannelTimestamp IS     NULL THEN (UNIX_TIMESTAMP(now()) - UNIX_TIMESTAMP(joinChannelTimeStamp))\n            WHEN leaveChannelTimestamp IS NOT NULL THEN (UNIX_TIMESTAMP(leaveChannelTimestamp) - UNIX_TIMESTAMP(joinChannelTimeStamp))\n            ELSE -1\n        END AS \"TimeSpent\"\n    FROM discord.voiceChatLog\n    WHERE\n        (\n            (UNIX_TIMESTAMP(joinChannelTimeStamp) < $__unixEpochFrom() AND (UNIX_TIMESTAMP(leaveChannelTimestamp) > $__unixEpochTo() OR leaveChannelTimestamp IS NULL))\n            OR $__timeFilter(joinChannelTimeStamp)\n            OR $__timeFilter(leaveChannelTimestamp)\n            OR\n            (\n                leaveChannelTimestamp IS NULL\n                AND (UNIX_TIMESTAMP(now()) - $__unixEpochTo()) <= 5\n            )\n        )\n        AND (userName IN ($User) OR \"All\" IN ($User))\n        AND (channelName IN ($Channel) OR \"All\" IN ($Channel) OR channelId IS NULL)\n    GROUP BY id\n) AS t1\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "User Activity By Channel",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT * FROM\n(\n    SELECT\n        CONCAT(userName, \"(\", channelName, \")\") AS metric,\n        CASE\n            WHEN channelId IS     NULL AND leaveChannelTimestamp IS     NULL THEN UNIX_TIMESTAMP(now())\n            WHEN channelId IS     NULL AND leaveChannelTimestamp IS NOT NULL THEN UNIX_TIMESTAMP(leaveChannelTimestamp)\n            WHEN channelId IS NOT NULL AND leaveChannelTimestamp IS     NULL THEN UNIX_TIMESTAMP(now())\n            WHEN channelId IS NOT NULL AND leaveChannelTimestamp IS NOT NULL THEN UNIX_TIMESTAMP(leaveChannelTimestamp)\n            ELSE 0\n        END AS \"time\",\n        CASE\n            WHEN channelId IS NULL THEN 0\n            WHEN leaveChannelTimestamp IS     NULL THEN (UNIX_TIMESTAMP(now()) - UNIX_TIMESTAMP(joinChannelTimeStamp))\n            WHEN leaveChannelTimestamp IS NOT NULL THEN (UNIX_TIMESTAMP(leaveChannelTimestamp) - UNIX_TIMESTAMP(joinChannelTimeStamp))\n            ELSE -1\n        END AS \"TimeSpent\"\n    FROM discord.voiceChatLog\n    WHERE\n        (\n            (UNIX_TIMESTAMP(joinChannelTimeStamp) < $__unixEpochFrom() AND (UNIX_TIMESTAMP(leaveChannelTimestamp) > $__unixEpochTo() OR leaveChannelTimestamp IS NULL))\n            OR $__timeFilter(joinChannelTimeStamp)\n            OR $__timeFilter(leaveChannelTimestamp)\n            OR\n            (\n                leaveChannelTimestamp IS NULL\n                AND (UNIX_TIMESTAMP(now()) - $__unixEpochTo()) <= 5\n            )\n        )\n        AND (userName IN ($User) OR \"All\" IN ($User))\n        AND channelId IS NOT NULL\n        AND (channelName IN ($Channel) OR \"All\" IN ($Channel))\n    GROUP BY id\n    UNION\n    SELECT\n        CONCAT(userName, \"(\", channelName, \")\") AS metric,\n        UNIX_TIMESTAMP(joinChannelTimeStamp) AS \"time\",\n        CASE\n            WHEN channelId IS NULL THEN 0\n            WHEN leaveChannelTimestamp IS     NULL THEN (UNIX_TIMESTAMP(now()) - UNIX_TIMESTAMP(joinChannelTimeStamp))\n            WHEN leaveChannelTimestamp IS NOT NULL THEN (UNIX_TIMESTAMP(leaveChannelTimestamp) - UNIX_TIMESTAMP(joinChannelTimeStamp))\n            ELSE -1\n        END AS \"TimeSpent\"\n    FROM discord.voiceChatLog\n    WHERE\n        (\n            (UNIX_TIMESTAMP(joinChannelTimeStamp) < $__unixEpochFrom() AND (UNIX_TIMESTAMP(leaveChannelTimestamp) > $__unixEpochTo() OR leaveChannelTimestamp IS NULL))\n            OR $__timeFilter(joinChannelTimeStamp)\n            OR $__timeFilter(leaveChannelTimestamp)\n            OR\n            (\n                leaveChannelTimestamp IS NULL\n                AND (UNIX_TIMESTAMP(now()) - $__unixEpochTo()) <= 5\n            )\n        )\n        AND (userName IN ($User) OR \"All\" IN ($User))\n        AND channelId IS NOT NULL\n        AND (channelName IN ($Channel) OR \"All\" IN ($Channel))\n    GROUP BY id\n) AS t1\nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "Users Channel Activity",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  id AS \"time\",\n  channelName AS metric,\n  count(*) AS \"joins\"\nFROM discord.voiceChatLog\nWHERE\n    (\n        (UNIX_TIMESTAMP(joinChannelTimeStamp) < $__unixEpochFrom() AND (UNIX_TIMESTAMP(leaveChannelTimestamp) > $__unixEpochTo() OR leaveChannelTimestamp IS NULL))\n        OR $__timeFilter(joinChannelTimeStamp)\n        OR $__timeFilter(leaveChannelTimestamp)\n        OR\n        (\n            leaveChannelTimestamp IS NULL\n            AND (UNIX_TIMESTAMP(now()) - $__unixEpochTo()) <= 5\n        )\n    )\n    AND (userName IN ($User) OR \"All\" IN ($User))\n    AND channelId IS NOT NULL\n    AND (channelName IN ($Channel) OR \"All\" IN ($Channel))\nGROUP BY channelId, channelName,2\nORDER BY count(*)"
    }
   ]
  },
  {
   "title": "Channel  Users Current",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  id AS \"time\",\n  channelName AS metric,\n  count(*) AS \"joins\"\nFROM discord.voiceChatLog\nWHERE\n    leaveChannelTimestamp IS NULL\n    AND (userName IN ($User) OR \"All\" IN ($User))\n    AND channelId IS NOT NULL\n    AND (channelName IN ($Channel) OR \"All\" IN ($Channel))\nGROUP BY channelId, channelName,2\nORDER BY count(*)"
    }
   ]
  },
  {
   "title": "Total Time By User",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT metric, time, sum(TimeSpent)\nFROM\n(\n    SELECT\n        userName AS metric,\n        0 AS time,\n        CASE\n            WHEN leaveChannelTimestamp IS     NULL THEN (UNIX_TIMESTAMP(now()) - UNIX_TIMESTAMP(joinChannelTimeStamp))\n            ELSE (UNIX_TIMESTAMP(leaveChannelTimestamp) - UNIX_TIMESTAMP(joinChannelTimeStamp))\n        END AS \"TimeSpent\"\n    FROM discord.voiceChatLog\n    WHERE\n        (\n            (UNIX_TIMESTAMP(joinChannelTimeStamp) < $__unixEpochFrom() AND (UNIX_TIMESTAMP(leaveChannelTimestamp) > $__unixEpochTo() OR leaveChannelTimestamp IS NULL))\n            OR $__timeFilter(joinChannelTimeStamp)\n            OR $__timeFilter(leaveChannelTimestamp)\n            OR\n            (\n                leaveChannelTimestamp IS NULL\n                AND (UNIX_TIMESTAMP(now()) - $__unixEpochTo()) <= 5\n            )\n        )\n        AND (userName IN ($User) OR \"All\" IN ($User))\n        AND channelId IS NOT NULL\n        AND (channelName IN ($Channel) OR \"All\" IN ($Channel))\n) AS t1\nGROUP BY metric, time\nORDER BY sum(TimeSpent) ASC"
    }
   ]
  },
  {
   "title": "Channels Activity Time Summary",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, metric, sum(TimeSpent)\nFROM\n(\n    SELECT\n        UNIX_TIMESTAMP(joinChannelTimeStamp) AS \"time\",\n        channelName AS metric,\n        channelId,\n        channelName,\n        id,\n        CASE\n            WHEN leaveChannelTimestamp IS NULL THEN (UNIX_TIMESTAMP(now()) - UNIX_TIMESTAMP(joinChannelTimeStamp))\n            ELSE (UNIX_TIMESTAMP(leaveChannelTimestamp) - UNIX_TIMESTAMP(joinChannelTimeStamp))\n        END AS \"TimeSpent\"\n    FROM discord.voiceChatLog\n    WHERE\n        (\n            (UNIX_TIMESTAMP(joinChannelTimeStamp) < $__unixEpochFrom() AND (UNIX_TIMESTAMP(leaveChannelTimestamp) > $__unixEpochTo() OR leaveChannelTimestamp IS NULL))\n            OR $__timeFilter(joinChannelTimeStamp)\n            OR $__timeFilter(leaveChannelTimestamp)\n            OR\n            (\n                leaveChannelTimestamp IS NULL\n                AND (UNIX_TIMESTAMP(now()) - $__unixEpochTo()) <= 5\n            )\n        )\n        AND (userName IN ($User) OR \"All\" IN ($User))\n        AND channelId IS NOT NULL\n        AND (channelName IN ($Channel) OR \"All\" IN ($Channel))\n) AS t1\nGROUP BY channelId, channelName,2\nORDER BY sum(TimeSpent)"
    }
   ]
  }
 ]
}